sudo: false
language: c

addons:
  apt:
    packages:
    - pandoc

branches:
  only:
  - /^\d+?-?\w+?$/

env:
  global:
  - secure: boy5pj5gemC0rFD46bK/pwklg7dfSYu040MZpOEjJAccuw1stobty0UKjQOajLW5GLfTcx8YDNXaWQ9H/P3ZEvNjBhMBbRznWLmCgzUFYKRKPdgZDlSvkQ1wttyvFOvilXgOBdZJr1cF3eYjGqSEVqfna77fa7RmV3VmxR+jKawhM3KAnwnjKTIjZnmkxD6jkGHxSLAwChWMXf0P5yrfQvcnAY+Jn3a1Hilr9o8SLb8lPEoGMJqLP3EdvQJwy2viuvhNYXn4cNtjZEJyaOeA3SV9WjlyRelnJwazeyCfN9PbQvZ2CsUfxZ+hji1+G3/P1JRH6YwSQ9uw/7FLwNEnyoJSOwobyhy0sNWsgdwtZD6BePBFr9cJkUcMgVvRNqXppsmS25HmAjjjqXqVHBPx2lO1O+V0X1UYtD5Az/ZKHYWRdwHWZrG2C0hEm9tSD7As2GYVELGFs3o9QN9t9ZrcoQAumm5cL9R4Kc0eX6b7RAga8MHvVLQiqtjVhHoRC4Qq8m7Pzmw+H5Lgp9GDdwM176vf5S98qc0CrtPPqZWSXUuula73zrS6OlpLj96EQuIfGZYDO4ywIpKwxAX7957UPPB7ZWoi1e6pmwZlJGnIX4QB0jo3ceShjkM0Ip2wRz8tMBpFWBrwUd1wFqicX7k1lm+74AtQJFLGKGJ4VFrL4LU=
  - secure: EI0wgEzO35jsPQVTXJ6bQyUIrhIo94sO/zi3bPzmZzZlG8mLux68QSWneSts88+8ST9Yuta+Mo6k8gG7dIJRXEa66j8si5Vp8HHB48jhACGbRMTdT+E/xQHyTZ30DU36ab46wNSQZPFmlCfvxJfepemql2HsoQRrFARGyi2oDiQeGctqfvgl1M1VaYiPowOqV0HNCYUH1p+iSekiD03y7eMkNt7wIwk7nxeSpxO5fSbn7jPP1xXu9e/ECrV1Wcxcl/UhAbO3AVszu+VpRK5QiprvwKGV4FsdlN6wX0pm+XDPiB9NwZyifMW+IMPgPuikqEyhp32cRWO4WpYNmA+WoHYrbBrFK0FjsG/dC12NiXsPiJzZi6h+0beFh2flnfk+cECDZz5eKGDaILqrv8k4ceRS5NM0T1RCuMSYe2UWZTxgluXSlyM9Z+18tTcpLrZt0HrMbY0UnBnxcV7zegdcNpwFXV3rEPeTdmBBWsXQiTZTl3yCxHTUAYpF3hmknT3osiMgeHYuJ5rG6h2Jb0/cm+rCdMp3YX1pe0hXpxFnHNI6Cyq0wvdQW9j5GZ8PIbji86NTU2Mua15jaRz8GoyegzbKU18W9SIkWiKI4KrMeMMTJ04SZLRRWy1XHF6J8EeQWfEle7gyva6rOGju8/haK6UG1IX/SD1+Ee+xhQXxwmU=

script: curl -s https://raw.githubusercontent.com/oUF-wow/packager/master/release.sh | bash

notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      secure: eZSDumrIkgdlADxxAKGO3eVBz5hrTpiYAPSuI2mDO0JnYiSyE2ZmJar/c+1LRlJlcbJg8oQx/UzUqX4QCs+nk4tOocFbfoKu+LXOUFNuk8FQ4SqfCxqJsqvKllOyJ1Q6kEmTyztiTBbpa0qkB0h13TS1iYFlrD5qEOBfSS683x12fWY5N22oujBWXmEiGwRkFS2HqQwIP8vPttyIqF/UAwOOk+wS0uSi/kQS6SesZXshBYLBwxU443L9trtFu3uKHVzj09mcP5ncyiyYdDRhHgIrlTmOoOhFnuDBJ9TaaDWPGp4MhrVHI4DPDVyK1a/8OV58peToC8C+pHziMitbPD7zf+LIZmCW7wvQAXa2kCObPETAqloXqzcTMp0xFUbmsB1OsJWH3nckhjdcvtpZgRMznZq9NHg0fjh9XK/5pIs7JI+M2SD4ZyWdbFASOOUS6OW4qLAXJ+isoQ4o8nV1sy69hAydkmBdy+tvtM+cqiDhjW5+C4E1GDdEi2BgWLS0tIAUkn9sUh8Jy2SzmaV099C6gchRsNjX55NjETwhwxX4wO+upKkHtoyMBP8ZnkPzSWnxCWct7wzdDEZIzEEkST0QBDks0aK7SWTdCrSYLJuaGGru6rINt30y3nTyLgSYTrYdF2LW0fDfJguw+t1KgsL5x7nKgqaldD7lOfMHhiA=
