language: python

python:
  - "3.6"

branches:
  only:
    - master

before_script:
  - openssl aes-256-cbc -K $encrypted_5980be8a6828_key -iv $encrypted_5980be8a6828_iv -in .travis/deploy.enc -out "$HOME/.ssh/deploy" -d
  - chmod 600 "$HOME/.ssh/deploy"
  - echo -e "Host github.com\n\tIdentityFile $HOME/.ssh/deploy\n" >> $HOME/.ssh/config
  - git config --global user.email "$GIT_EMAIL"
  - git config --global user.name "$GIT_NAME"

script:
  - git clone "git@github.com:$TRAVIS_REPO_SLUG.wiki" .wiki
  - python3 .travis/wiki.py
  - cd .wiki
  - git add .
  - git commit -m "$TRAVIS_COMMIT"
  - git push origin master

env:
  global:
    - secure: jEDTbxNs+HU1A1hf4O5AIvt4KFAMxwRUPAG9TJx2H06VEaRTeMvwCfGNRpfOcMX8FCp4qeU2mc9IDNnDKEpxjXOzhZGP6Bpm6jumNr/ruUngNtFVWHNVU5SgomuqiQISxH6Yr6ZAS7HcXCbWdkFT3NV8IqMwhyiqLRVnMeyjmPQTOfK2v/nIoeMUH46uGfXr6OspPe60glx/+c22namZW39lF+0ir/Yvb/WPqtX3Ihjo/I17+UhypRoIjyxdw+GZPfYOepuJPQKv5y5QtIspaEn4goPRIm0E3kzT1JTwdQKaGV6Ru3iu8QJogIT3gW6oixv5hEZrZamAdBeGZ/AxhGVG4ot2AnErw2JmEiECgj9dbU1O1xd7yd+dJv1zu8m9gIQ6UQN/JuhHyoABu50SSp1cW4U9jE1hEUW7lUVe38tkEJoP6hffGHtC5thmfhLPCf8NZctLdWFhDyvHLn5rPaokzHqHqw2750lCpM9PGliksFGCr2WCPfHK/Ben+AMkbOnoTT3nzcwse58eA7UlWq2T58BzDf7S3uCBnFIWKW4LujoSXtFynAOm9APyb3ZyCcdv8eAVxCBo2oXjqxScHCf/qpWUsNxU6Uxm6Vq4u9aIIxY6Ea6iU5k7TtVZHG4QRI9FxaVFIC9xjxOgiY1DOc4zF51GGCCQWLmwhEi+gY0=
    - secure: Ty+w0gJi2V4uzq6phEZgldxsq/gxKdSoYl6Z2xKiiGjYQHRM4yu0k7oKcH45qm5PHK8Vz3pgSGr3RXqfBs0euzgjeP6NgXU3fflxxz61kmuBIwb77omR/6OXzozKBNXo6KSnvkcfbWn9ehHtiYDyvBJ07OaVuPtU6zw70dJSom8P9+xhewIa9e5xqGVBIL9ReSsryLs3j+WwFJOmFKbvwn83ObJ3a5W05lXncdBQion9Tm6uOMeoLOzVWbuxQVIm4fNKdNho386OG5TcRo6IIpe1jnoz87v4lVz1Fm8tikgO7xQXFwJm94/+qvkzdvfGQNxNL9J6WYjwVzez+pnbNU4w4NefxlxvL6PVLI98WE4IQUx0edDSACKee5fC5GIxiv35kyCOUSj4k9/hekAd9bzMrwpi3tzrPBG/mD2c5TwGDGaii5mZi4n6pdkLAJeUNJlnkO+73fFTmr/2wBzkqxEqKAMNypqoW80SLqN5P8+GfGql7RD71x7QxCRaDItsycqSsJwiTLRCCDp224Jt4KTM10/lbPDwQx9N1GvACHdKQWlYHxEgQ5KRrCVBUmMweWC9YIOAJHL/s8DK9eWBZkgupxBCqMHk2bsP5QPnJbR8YNuAyxa+lUfKg9aQWG+AgoikcSRyHbO312tyD2n7C60lau1Zit4JqX1FSXmUB7c=
